### ISSUE TITLE
Replace Help us plan section with Unconference summary

### ISSUE THREAD

**Issue by katjam** [elm-camp/website#15]
![image](https://github.com/elm-camp/website/assets/861172/f1966ed4-0088-4fc9-a033-6ec1e4f4425e)

Replace with vague summary inspired by info from prospectus, like this:
![image](https://github.com/elm-camp/website/assets/861172/eaa445be-64f6-41be-ae46-66e79093a920)

**Comment by jxxcarlson** [comment]
This is taken care of by PR 'https://github.com/elm-camp/website/pull/29'

**Comment by katjam** [comment]
I think we can close this for now and make improvements as we notice them.
