### ISSUE TITLE
Review unconference guidelines for accuracy and update

### ISSUE THREAD

**Issue by katjam** [elm-camp/website#21]
https://elm.camp/unconference-format

**Comment by wolfadex** [comment]
> There are 2 pre-planned sessions (the unkeynotes at the start and end of Elm Camp)

Do we still want 2 of these?

> We'll start with 3 tracks. If needed, more concurrent sessions may be scheduled during the unconference.

This still sounds good to me.

> Sessions will be offered in 15 and 30 minute blocks.

I thought there was talk of extending some sessions last year but I don't fully remember. Does anyone else remember?

> We'll arrange collective scheduling sessions every morning,

I remember discussions about this but don't remember what was decided.


Everything else here looks good to me.

**Comment by katjam** [comment]
- I think we should remove the unkeynotes from the format docs, so we are not promising anything
- Sure, stick on the 3 tracks
- There was talk of extending: maybe we should be more vague and say there will be short and long session blocks available
- How about there will be collective scheduling sessions periodically? I also can't remember what we actually did.
